name: TribalTrove
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=3.2.0-162.0.dev <4.0.0"


dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  dropdown_button2: ^2.3.9
  carousel_slider: ^4.2.1
  calendar_date_picker2: ^0.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter

 
  flutter_lints: ^2.0.0


# The following section is specific to Flutter packages.
flutter:
 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Inter Bold
      fonts:
        - asset: assets/fonts/Inter-Bold.ttf
          # style: bold
    - family: Inter Medium
      fonts:
        - asset: assets/fonts/Inter-Medium.ttf
          # weight: 700
    - family: Inter Light
      fonts:
        - asset: assets/fonts/Inter-Light.ttf
          # style: light      
    - family: Inter Regular
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
          # style: regular 
    - family: Inter SemiBold
      fonts:
        - asset: assets/fonts/Inter-SemiBold.ttf
          # style: bold           
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
